# See: https://circleci.com/docs/configuration-reference
# https://circleci.com/docs/language-python/ for more details
version: 2.1

# See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
executors:
  my-executor:
    docker:
      # See:https://circleci.com/developer/images/image/cimg/python
      - image: cimg/python:3.9

# See: https://circleci.com/docs/orb-intro/
orbs:
  # See : https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.1.1

# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    executor: my-executor
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: build-requirements.txt
      - run:
          name: Build the package
          command: |
            python setup.py bdist_wheel
      - run:
          name: Install the package
          command: |
            pip install dist/*.whl
      - run:
          name: Run tests
          command: |
            coverage run -m pytest --junitxml=test_results
      - store_test_results:
          path: test_results
      - run:
          name: Coverage report
          command: coverage report
      - run:
          name: Coverage HTML
          command: coverage html
      - store_artifacts:
          path: coverage_report
  publish:
      executor: my-executor
      steps:
        - checkout
        - run:
            name: Install Twine
            command: |
              python -m pip install --upgrade pip
              pip install setuptools wheel twine
        - run:
            name: Build the Package
            command: python setup.py sdist bdist_wheel
        - run:
            name: Publish to PyPI
            command: |
              twine upload dist/* -u __token__ -p $PYPI_TOKEN
  hold:
    type: approval  # This job will require manual approval
    steps:
      - run:
          name: Manual Approval
          command: echo "Waiting for manual approval to proceed with publishing."

# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  build_and_release:
    jobs:
      - build-and-test
      - hold:
          requires:
            - build-and-test
      - publish:
          requires:
            - hold
          filters:
            branches:
              only:
                - /^release\/v\d+\.\d+\.\d+$/